name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov bandit cyclonedx-bom

      - name: Run flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Bandit security scan
        run: |
          bandit -r calculator/ -f html -o bandit-report.html

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python -m pytest --cov=calculator --cov-fail-under=80 tests/
      
      - name: Generate coverage HTML
        run: coverage html

      - name: Generate SBOM
        run: cyclonedx-py -o sbom.json

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
  
  docker-image:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ss-ola3 .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Push Docker image to GHCR
        run: |
          docker tag ss-ola3 ghcr.io/${{ github.repository_owner }}/ss-ola3:latest
          docker push ghcr.io/${{ github.repository_owner }}/ss-ola3:latest

